apiVersion: serving.knative.dev/v1
kind: Service
metadata:
    name: node-benchmark-min0
    namespace: default
spec:
    template:
        metadata:
            annotations:
                autoscaling.knative.dev/min-scale: "0"
        spec:
            containers:
                - image: kind.local/node-benchmark:v1
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 8080
